# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettype',
            old_name='asset_type',
            new_name='name',
        ),
    ]
