# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocosign', '0003_auto_20151119_2146'),
        ('assetstracker', '0003_auto_20170202_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('djangocosign.country',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('djangocosign.office',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assetstracker.Country'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='assetstracker.Office'),
        ),
    ]
