# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracker', '0005_auto_20170222_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='no',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='No'),
        ),
    ]
