# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-22 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocosign', '0003_auto_20151119_2146'),
        ('assetstracker', '0008_auto_20170222_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetIssuanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('return_date', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Custodian',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('djangocosign.userprofile',),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assettype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assetstracker.AssetType'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assetstracker.Category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assetstracker.Donor'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assetstracker.Status'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assetstracker.Subcategory'),
        ),
        migrations.AddField(
            model_name='assetissuancehistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetstracker_assetissuancehistory_created', to='djangocosign.UserProfile'),
        ),
        migrations.AddField(
            model_name='assetissuancehistory',
            name='custodian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custodian_history', to='assetstracker.Custodian'),
        ),
        migrations.AddField(
            model_name='assetissuancehistory',
            name='issued_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuedby_history', to='assetstracker.Custodian'),
        ),
        migrations.AddField(
            model_name='assetissuancehistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_history', to='assetstracker.Asset'),
        ),
        migrations.AddField(
            model_name='assetissuancehistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assetstracker_assetissuancehistory_updated', to='djangocosign.UserProfile'),
        ),
    ]
