# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracker', '0010_auto_20170326_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetissuancehistory',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuedby_history', to='assetstracker.Custodian'),
        ),
    ]
