# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-28 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracker', '0011_auto_20170326_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetissuancehistory',
            old_name='issue_date',
            new_name='issuedate',
        ),
        migrations.RenameField(
            model_name='assetissuancehistory',
            old_name='issued_by',
            new_name='issuedby',
        ),
        migrations.RenameField(
            model_name='assetissuancehistory',
            old_name='return_date',
            new_name='returndate',
        ),
    ]
