# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-04 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetstracker', '0012_auto_20170328_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='asset',
            name='broken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='custodian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetstracker.Custodian'),
        ),
        migrations.AddField(
            model_name='asset',
            name='disposed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
